language: haskell
sudo: false
cache:
  directories:
  - $HOME/.stack/
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.3.1/stack-0.1.3.1-x86_64-linux.gz
  | gunzip > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack
- stack --no-terminal setup
install:
- stack setup --no-terminal
- stack build --only-snapshot --no-terminal
script:
- stack build --pedantic --no-terminal
deploy:
  - provider: releases
    username: agrafix
    password:
        secure: Ystf0J7oQ3VBJblXDNKUk5/wgKJjk7JGBNReHCT3PbF6VBVLT6B6fJFfC/O9zYm3/chzcGL092lLeJmNQpPI/F63MhYgtGQACvfl93MEGDgNeGdYkOMeDATc2QhtztmT79uFw1NOFhXssHidiCBHsWXvkmcHsFT6uKMeGqRtJojuVpuIXX9XstwybGIV+pv2ovZY5Q2wMErG19tzPVu9Vt9gdMKoGHPCSDeFL5wTnM+Zct6F1MQSu0VDOe2JTk7c6B7UfpUxTVZ1BDr/jTZN6bIs/McjifvT4k9fqKhZJEByUtRvO8zqHqoL9PxqnkjYp+7qOwpe7AqPG5j5+ZHSM7RM7zl85DbJYy0KgxpNfStpv8o4VxPmNx97SvYre+qo3JlzelyZPKOk7nwxsZpVNRg0uYlcGsc91UvGPkKdMyM2GqjEtoqeDR/1bBgTqMNXdXYWrImhs1PPEVLYs787DJAiskkmEYgAZIiACki8lVbbZSiyWa976SU85c8h7qTK2Cr3xtKbsZnoP9HYauMkYqNIyX7r9OHjNcqoBKJ1dswDMTzlJfs3p/PlgCpXjwNKGlqqweYv1pqqTBpX3L8WqetLLa2UwUgjn+f78CadfB/HqEZvmeRwWzsqhESAWoizTX1eJmurb6d64tHdV4fWev3Mt+7pnCzVCfnWbwxQxqg=
    file: ~/.local/bin/twirec
    skip_cleanup: true
    on:
      tags: true
  - provider: hackage
    username: AlexanderThiemann
    skip_cleanup: true
    on:
      tags: true
    password:
      secure: R7G+GG5pKJaohCEumXsGwcVkpVeqHKXM8pgvNeeEcF+6iHHtVu8gyVV9Ow/F3UFY6hOqSaMMi550OKQrlsw5N4OhGco3cA5mg+5EKdzPAtivwQwQZZkpXktgyxalZgq1Ce1VLqNi2rL5XTVKd8cWz2f3FlYbsxZdiHEdFZ0R95LizwhaIWpB+ndyK1+aqGfWHWXmA80pQKq2TzY3mlkHzEIMGwD2zZ2u2+FKEX9HwAzTAun0qaKJ6BQg5G0WnkPrb8OaFGtVVA2Mw6JijDRmvL/9b9C4kIN8fg85SqHrbcaxmbPq6rzCjwF3S4l95k51uQg0UuTa5ywMzl0gzZFUjexo6vxrpgAPSQxKdwIUeshdIvyTUvVDTcE73a7Sj2kzI1o9oYoFspLobeVKE7U00jOB/sjdFO3LSSnbQpsp5Ht4Kzs0a3U785A4l9YJJMhYnusHhstzHYEj6sL3fSs2EMh6+ImdhhZ4msJUiL0sZ7wCQaGpcJILClMSkgNhpav8zYa6xx09rueRxSf7BE2ZAyWqLYcXLWeRmzWjvzTl8X1fU1ysDV6395hroVcvzQfC6wt+ftCkVasyfvLEpPG0ML/no5DTjNlHTR6X6NvrxXkQ8EiRoHsXMdahsAcCb9CwHc6RIh1JTKaAJw6Fw1XnYs9WAmvDDSH72HWZ6diwdOM=
