language: node_js
node_js:
- '4.0'
sudo: false
env:
  global:
    secure: fM427PrRVCgKflSjbVSfRmBdCeSJ9ATZl7eS9rNb9BIKtIj3V9qLXhOtXTGVdsUEyJBeynH9Q3YtbokKWPW4mOncsk6+fwHZrhP/cH5WcUvqgrPtQVV/14U1ykmTAMPGXI8Roy82zb1Bcn1u6I7ltrVJ39QV8XRVyRHibvkyIzy8p7F0Qy1Ca62ov0HjSZhwqKDxYAKJJgm7KO33l1DxSRTu8AV8gtBF1g9cjW7Nr5v1LQIL40DqdD3pAvGRnD2QBS6N76pP/qQEnIjfU6CTSnYSI8IGBzrNU1NisFCXpbdDTwJ+T+JOV2z4rinHCA0P410WfjoHV/VvRYt0EIYxOjgEJhX/G3rqmcmMQ2o9wfXryu28vIryqc7SCAFYGh4RxlcsHS1x7gB7k+Gc+/8thc8WmNfNx2cVgui3MtJreWAjY0K84qFelbbocdWA83mBWnpfyZf9R59jyX6eV4lPBrolE+VSc494stJKiBYi1NuZ8Om7L44cfzN8FQAY2L09ONL33Wsi/yw8fOtqDAfvcPNWn6CDuyE1Maww/KZ831di38dezH4uvLcN/h8/IPvmka10RlT5LqD2Kfn4XoIaVy9jBVFsURrxthSO2RYZUqeSVy8SWgg8N2Qq64pG4S3SoMt6AgtODEFRc/9WpPNvXNxOneMzWMmXqwuAh19sxXs=
cache:
  directories:
  - $HOME/.stack/
  - $HOME/.nvm/
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- stack --no-terminal setup
install:
- npm install -g pulp@6.1.0 purescript@0.8.2 bower@1.7.2
- stack build --only-snapshot --no-terminal
script:
- stack test --pedantic --no-terminal
before_deploy:
- export RELEASE_FILE=$(stack exec -- which twirec)
- echo "Binary $RELEASE_FILE will be deployed to GitHub"
deploy:
- provider: releases
  api_key:
    secure: fTRzmC53IsYLJKX7jHFoo7wQEWagoDEihJ/3wSH40vzzLI7LgyrLR0eS9H92NVrk31v//IxRVNd5I6RE/8i1V4NO4VdxhjM2BP+painMemgCIxX6hhP+IF1q8+x4vtOFD4WvN+6UmJNI+K4o0WjfFjIaXpkxqJgmF7lrF9fzuOdTSj76ZsdO51WNrRFVDRAbf94eLoJbGkTeAFJiPUbI+LQ/AQcHrw7VFB/XkMmTc4bUJMMXmdkxk7RRU2Vma2t7sY/JNhcSajeHIYiMjHe0M9+x3cbPRwriOEmJUeccBg0+sA8UTTji3H+UEhAI1pIPJGwXGKLW/IED76VzeO6S5pIQaPPD8N3qWnULs2zdwIAliP2BBPG1BOK62Ck8FhKVqB1vND5wpsFcIebEOmdVZuGbQFw9VBWTiXhjUjO0Sg/LaoTHQp6muY3G+HyDxwVe5Twqsb4Jz7ydpRzELT0iMnaJTH9XvJ4nVkRuCqyJsxuioewhBSDIl7guHNyrTjIsuEc9OJDG93GkQS7kapehq3QNmcvtkG0+Ru2U9tcxoZZZ1Mqc5TfA1JCUbZ3RvalvzFGz/hm/BNdhXUKz51MvA9e1vhhpp9/1AAHdSX5TRnWeF7hkR8FpqMyZuQXIfNsatqua+KXELTbQ0IbbPx4u0TOwTO0Xc97eik8LOZ/qQhc=
  file: ${RELEASE_FILE}
  on:
    tags: true
- provider: script
  script: scripts/deploy-hackage.sh
  on:
    tags: true
